version: '3.3'

volumes:
  pg_data:
  static_data:
  media_data:


name: volunteers

services:

  db:
    image: postgres:13.0-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ../backend/
      args:
          - PYTHON_VERSION_BUILD=${PYTHON_VERSION_BUILD}
    env_file: .env
    volumes:
      - static_data:/backend_static
      - media_data:/app/media
    command:
      - /bin/sh
      - -c
      - |
        python manage.py collectstatic -c --noinput
        cp -r /app/collected_static/. /backend_static/static
        python manage.py makemigrations
        python manage.py migrate
        gunicorn --bind 0.0.0.0:8000 backend.wsgi
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: https://github.com/volunteers-for-city-projects/volunteers-frontend.git#develop
      args:
        - SECRET_KEY=${REACT_APP_SECRET_KEY_RECAPTCHA}
    command:
      - /bin/sh
      - -c
      - |
        cp -r /app/. /static_files/
    volumes:
      - static_data:/static_files

  nginx:
    image: nginx:1.25.2-alpine3.18-slim
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/usr/share/nginx/html
      - media_data:/usr/share/nginx/html/media/
    depends_on:
      backend:
        condition: service_started

  redis:
    image: redis:alpine3.18
    hostname: redis
    expose:
      - 6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery:
    build:
      context: ../backend/
      args:
          - PYTHON_VERSION_BUILD=${PYTHON_VERSION_BUILD}
    env_file: .env
    volumes:
      - static_data:/backend_static
      - media_data:/app/media
    command: celery -A backend.celery_app worker -l info
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy

  celery-beat:
    build:
      context: ../backend/
      args:
          - PYTHON_VERSION_BUILD=${PYTHON_VERSION_BUILD}
    env_file: .env
    volumes:
      - static_data:/backend_static
      - media_data:/app/media
    command: celery -A backend beat -l info
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy
